Proyecto Final Graña Zapata/AppLectores/Proyecto/AppLectores/urls.py
from django.urls import path
from AppLectores.views import *

urlpatterns = [
    path("", inicio, name="home"),
    path("login", iniciar_sesion, name= "Login"),
    path("registrar", registrar, name= "Registro"),
    path("logout", cierre_sesion, name= "Cierre"),
    path("editar", editar_usuario, name= "Editar"),
    path("contra", CambiarContra.as_view(), name= "Contra"),
    path("avatar", agregar_avatar, name= "Subir Avatar"),
    path("about", acerca, name= "about"),

    path("ver_escritor", ver_escritor, name="Escritor"),
    path("crear_escritor", crear_escritor, name= "Crear Escritor"),
    path("actualizar_escritor/<escritor>", actualizar_escritor, name= "Editar Escritor"),
    path("borrar_escritor/<escritor>", borrar_escritor, name= "Eliminar Escritor"),

    path("ver_lector", ver_lector, name="Lector"),
    path("crear_lector", crear_lector, name= "Crear Lector"),
    path("actualizar_lector/<lector>", actualizar_lector, name= "Editar Lector"),
    path("borrar_lector/<lector>", borrar_lector, name= "Eliminar Lector"),

    
    path("ver_libro", ver_libro, name="Libro"),
    path("crear_libro", crear_libro, name= "Crear Libro"),
    path("actualizar_libro/<libro>", actualizar_libro, name= "Editar Libro"),
    path("borrar_libro/<libro>", borrar_libro, name= "Eliminar Libro"),


    path("buscar_libro", buscar_libro, name= "buscar"),
    path("resultados_libro", resultados_libro),

    
    ] 

Proyecto Final Graña Zapata/AppLectores/Proyecto/Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("AppLectores/", include("AppLectores.urls"))
]


urlpatterns += static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyecto Final Graña Zapata/AppLectores/Proyecto/AppLectores/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from django.db import models

class Escritor(models.Model):
    nombre = models.CharField(max_length=100)
    nacionalidad = models.CharField(max_length=100)
    genero_preferido = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Libro(models.Model):
    titulo = models.CharField(max_length=200)
    autor = models.CharField(max_length=100)
    genero = models.CharField(max_length=50)
    
    def __str__(self):
        return self.titulo

class Lector(models.Model):
    nombre = models.CharField(max_length=100)
    edad = models.IntegerField()
    genero = models.CharField(max_length=50)
    preferencias_genero_literario = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre
    

class avatar(models.Model):

    usuario = models.ForeignKey(User, on_delete= models.CASCADE)
    imagen = models.ImageField(upload_to="avatares", null = True, blank= True)
    

Proyecto Final Graña Zapata/AppLectores/Proyecto/AppLectores/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class EscritorForm(forms.Form):
    nombre = forms.CharField(max_length=100)
    nacionalidad = forms.CharField(max_length=100)
    genero_preferido = forms.CharField(max_length=50)

class LibroForm(forms.Form):
    titulo = forms.CharField(max_length=200)
    autor = forms.CharField(max_length=100)
    genero = forms.CharField(max_length=50)
    

class LectorForm(forms.Form):
    nombre = forms.CharField(max_length=100)
    edad = forms.IntegerField()
    genero = forms.CharField(max_length=50)
    preferencias_genero_literario = forms.CharField(max_length=100)
    
class RegistroUsuario(UserCreationForm):

    class Meta: 

        model = User
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]



class EditarUsuario(UserChangeForm):

    password= None

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]



class AvatarFormulario(forms.Form):

    imagen = forms.ImageField()


Proyecto Final Graña Zapata/AppLectores/Proyecto/AppLectores/views.py
from django.shortcuts import render
from AppLectores.models import Escritor, Lector, Libro, avatar
from AppLectores.forms import *
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

def inicio(request):

    return render(request, "inicio.html", {"mensaje": "Disfruta"})

def acerca(request):

    return render(request, "acerca.html")
#Inicio y Registro

def iniciar_sesion(request):

    if request.method == "POST":

        formulario = AuthenticationForm(request, data = request.POST)

        if formulario.is_valid():

            info_dic = formulario.cleaned_data

            usuario = authenticate(username = info_dic["username"], password=info_dic["password"])

            if usuario is not None:

                login(request, usuario)
                
                return render(request, "inicio.html", {"mensaje": f"Bienvenid@ {usuario} a la Biblioteca"})
        
        else: 

            return render(request, "inicio.html", {"mensaje": "Error al iniciar sesión"})
    
    else:  

        formulario = AuthenticationForm()

    return render(request,"registro/login.html", {"formu": formulario})


def registrar(request):

    if request.method == "POST":
        
        formulario = RegistroUsuario (request.POST)

        if formulario.is_valid():

            formulario.save()

            return render(request, "inicio.html", {"mensaje":"Te has registrado correctamente."})

    else: 
        formulario = RegistroUsuario()       

    return render(request, "registro/registrar.html", {"formu": formulario})

@login_required 
def editar_usuario(request):
     
    usuario = request.user

    if request.method == 'POST':

       miFormulario = EditarUsuario(request.POST)
       
       if miFormulario.is_valid():

            informacion = miFormulario.cleaned_data

            usuario.email = informacion['email']
            usuario.last_name = informacion['last_name']
            usuario.first_name = informacion['first_name']

            
            usuario.save()

            return render(request, "inicio.html")

    else:

        miFormulario = EditarUsuario(initial={ "first_name": usuario.first_name,
                                                "last_name": usuario.last_name,
                                                'email': usuario.email})


    return render(request, "registro/editar_usuario.html", {"formu": miFormulario})


@login_required
def agregar_avatar(request):

    if request.method =="POST":

        formulario= AvatarFormulario(request.POST, request.FILES)

        if formulario.is_valid():
            
            info = formulario.cleaned_data
           
            usuario_actual = User.objects.get(username=request.user)
            nuevo_avatar = avatar (usuario= usuario_actual, imagen=info ["imagen"])
            
            nuevo_avatar.save()

            return render(request, "inicio.html", {"mensaje": "Creaste tu avatar"})
    
    else: 

        formulario = AvatarFormulario()

    return render (request, "registro/nuevo_avatar.html", {"formu": formulario})




def cierre_sesion(request):

    logout(request)

    return render (request,"inicio.html", {"mensaje": "Hasta pronto"})



#CRUD ESCRITOR

@login_required 
def crear_escritor(request):
    
    if request.method == "POST":

        formulario = EscritorForm(request.POST)

        if formulario.is_valid():

            info_dic = formulario.cleaned_data

            Escritor_nuevo = Escritor(nombre=info_dic["nombre"], 
                                  nacionalidad= info_dic["nacionalidad"],
                                  genero_preferido= info_dic ["genero_preferido"],
                                  )
            Escritor_nuevo.save()

            return render(request, "inicio.html")
        
    else: 

        formulario = EscritorForm()
        
    return render(request,"escritor/crear_escritor.html", {"formu":formulario})


def ver_escritor(request):
    
    todos_escritor = Escritor.objects.all()

    return render(request, "escritor/ver_escritor.html",{"total": todos_escritor})

@login_required     
def actualizar_escritor(request, escritor):

    escritor_elegido = Escritor.objects.get(id=escritor)

    if request.method == "POST":

        formulario = EscritorForm(request.POST)

        if formulario.is_valid():

            info_dic = formulario.cleaned_data

            escritor_elegido.nombre = info_dic["nombre"]
            escritor_elegido.nacionalidad = info_dic["nacionalidad"]
            escritor_elegido.genero_preferido = info_dic["genero_preferido"]

            escritor_elegido.save()
            
            return render(request,"inicio.html")

    else: 
            
            formulario = EscritorForm(initial={"nombre":escritor_elegido.nombre, 
                                               "nacionalidad": escritor_elegido.nacionalidad,
                                               "genero_preferido": escritor_elegido.genero_preferido})
    
            
    return render(request,"escritor/actualizar_escritor.html", {"formu": formulario})

@login_required  
def borrar_escritor(request, escritor):

    escritor_elegido = Escritor.objects.get(id=escritor)

    escritor_elegido.delete()

    return render(request, "inicio.html")




#CRUD LIBRO
@login_required 
def crear_libro(request): 
    
    if request.method == "POST":

        formulario = LibroForm(request.POST)

        if formulario.is_valid():

            info_dic = formulario.cleaned_data

            libro_nuevo = Libro(titulo=info_dic["titulo"], 
                                  autor= info_dic["autor"],
                                  genero= info_dic ["genero"],
                                  )
            libro_nuevo.save()

            return render(request, "inicio.html")
        
    else: 

        formulario = LibroForm()
        
    return render(request,"libro/crear_libro.html", {"formu":formulario})

     

def ver_libro(request):

    todos_libros = Libro.objects.all()

    return render(request, "libro/ver_libro.html",{"total": todos_libros})


@login_required  
def actualizar_libro(request, libro):

    Libro_elegido = Libro.objects.get(id=libro)

    if request.method == "POST":

        formulario = LibroForm(request.POST)

        if formulario.is_valid():

            info_dic = formulario.cleaned_data

            Libro_elegido.titulo = info_dic["titulo"]
            Libro_elegido.autor = info_dic["autor"]
            Libro_elegido.genero = info_dic["genero"]

            Libro_elegido.save()
            
            return render(request,"inicio.html")

    else: 
            
            formulario = LibroForm(initial={"titulo":Libro_elegido.titulo, 
                                            "autor": Libro_elegido.autor,
                                            "genero": Libro_elegido.genero})
    
            
    return render(request,"libro/actualizar_libro.html", {"formu": formulario})

@login_required  
def borrar_libro(request, libro):

    libro_elegido = Libro.objects.get(id=libro)

    libro_elegido.delete()

    return render(request, "inicio.html")


#CRUD LECTOR


@login_required 
def crear_lector(request):
    
    if request.method == "POST":

        formulario = LectorForm(request.POST)

        if formulario.is_valid():

            info_dic = formulario.cleaned_data

            lector_nuevo = Lector(nombre=info_dic["nombre"], 
                                  edad= info_dic["edad"],
                                  genero= info_dic ["genero"],
                                  preferencias_genero_literario=info_dic["preferencias_genero_literario"],
                                  )
            lector_nuevo.save()

            return render(request, "inicio.html")
        
    else: 

        formulario = LectorForm()
        
    return render(request,"lector/crear_lector.html", {"formu":formulario})
        


def ver_lector(request):
    
    todos_lector = Lector.objects.all()

    return render(request, "lector/ver_lector.html",{"total": todos_lector})

@login_required  
def actualizar_lector(request, lector):

    lector_elegido = Lector.objects.get(id=lector)

    if request.method == "POST":

        formulario = LectorForm(request.POST)

        if formulario.is_valid():

            info_dic = formulario.cleaned_data

            lector_elegido.nombre = info_dic["nombre"]
            lector_elegido.edad = info_dic["edad"]
            lector_elegido.genero = info_dic["genero"]
            lector_elegido.preferencias_genero_literario = info_dic["preferencias_genero_literario"]

            lector_elegido.save()
            
            return render(request,"inicio.html")

    else: 
            
            formulario = LectorForm(initial={"nombre":lector_elegido.nombre, 
                                              "edad": lector_elegido.edad,
                                              "genero": lector_elegido.genero,
                                              "preferencias_genero_literario":lector_elegido.preferencias_genero_literario})
    
            
    return render(request,"lector/actualizar_lector.html", {"formu": formulario})

@login_required  
def borrar_lector(request, lector):

    lector_elegido = Lector.objects.get(id=lector)

    lector_elegido.delete()


Proyecto Final Graña Zapata/AppLectores/Proyecto/AppLectores/templates/acerca.html
{% extends "padre.html" %}

{% block titulo %}
<h1 class="mb-5">Mundo de los libros</h1>

{% endblock %}

{% block parrafo %}

<p>Creamos esta página con el fin de que los lectores y escritores 
tengan su espacio para compartir, críticas, opiniones, 
que puedan interactuar con su escritor preferido. Además de otras. 
La idea es que con el tiempo, las próximas actualizaciones, 
se agregará una subscripción para poder "alquilar" los libros 
y puedas disfrutarlo de manera virtual sin ningun desperfecto.
</p>


{% endblock %}

Proyecto Final Graña Zapata/AppLectores/Proyecto/AppLectores/templates/inicio.html
{% extends "padre.html" %}

{% block titulo %}
<h1 class="mb-5">Bienvenidos a la Biblioteca Online!</h1>
{{mensaje}}
{% endblock %}

{% block barra %}

<div class="container">
    <a class="navbar-brand" href="#!">Inicio</a>
    <a class="btn btn-primary" href="#signup">Registrarse</a>
</div>

{% endblock %}

Proyecto Final Graña Zapata/AppLectores/Proyecto/AppLectores/templates/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Bibloteca Online</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}">Inicio</a>
                <a class="navbar-brand" href="{% url 'Lector' %}">Lectores</a>
                <a class="navbar-brand" href="{% url 'Libro' %}">Libros</a>
                <a class="navbar-brand" href="{% url 'Escritor' %}">Escritores</a>
                {% if user.is_authenticated %}
                <a href="{% url 'Editar' %} "> Hola {{user.first_name}} </a>
                <img src="{{user.avatar_set.last.imagen.url}}" width="60px" height="50px" alt="La imagen no cargó correctamente">
                <a class="btn btn-primary" href="{% url 'Cierre' %}">Cerrar Sesión</a>
                {% else %}
                <a class="btn btn-primary" href="{% url 'Login' %}">Iniciar Sesión</a>
                <a class="btn btn-primary" href="{% url 'Registro' %}">Registrarse</a>
                {% endif %}
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            {% block titulo %}

                            {% endblock %}
                            <!-- Signup form-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- * * SB Forms Contact Form * *-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- This form is pre-integrated with SB Forms.-->
                            <!-- To make this form functional, sign up at-->
                            <!-- https://startbootstrap.com/solution/contact-forms-->
                            <!-- to get an API token!-->
                            <form class="form-subscribe" id="contactForm" data-sb-form-api-token="API_TOKEN">
                                <!-- Email address input-->
                                <div class="row">
                                    <div class="col">
                                        
                                    </div>
                                    
                               
                                    </div>
                                </div>
                               
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Icons Grid-->
       
                        </div>
                    </div>
                    
                        </div>
                    </div>
                    <div class="col-lg-4">
                       
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Image Showcases-->
       
                    </div>
                </div>
                
                </div>
                
                    </div>
                </div>
            </div>
        </section>
        
                           
                        </div>
                    </div>
                    
                        </div>
                    </div>
                    
                        </div>
                    </div>
                </div>
            </div>
        </section>
        
                        
                        
                         
                            
                                </div>
                                
                            </div>
                            <!-- Submit success message-->
                            <!---->
                            <!-- This is what your users will see when the form-->
                            <!-- has successfully submitted-->
                            
                    </div>
                </div>
            </div>
        {% block parrafo %}

        {% endblock %}
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="{% url 'about' %}">Acerca de nosotros</a></li>
                            <li class="list-inline-item">⋅</li>
                            
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="https://www.facebook.com" target="_blank"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="https://twitter.com" target="_blank"><i class="bi-twitter fs-3"></i></a>
    </li>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://www.instagram.com" target="_blank"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>